print("\n\n====THE STUDENT NAME IS====")
print("1: Add Student ")
print("2: display student ")
print("3: search  Student ")
print("4: update  Student ")
print("5: delete  Student ")
print("6: Exit")
choice =int(input("Enter your choice:"))